change arch and platform

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -12,11 +12,11 @@ source "${plugin_dir}/lib/utils.bash"
 _download() {
   local _version="$1"
   local _bin_install_path=$2
-  local _artifact="go-containerregistry_Linux_x86_64.tar.gz"
+  local _artifact="go-containerregistry_${PLATFORM}_${ARCH}.tar.gz"
 
   local download_url="$GH_REPO/releases/download/v${_version}/$_artifact"
 
-  curl -Lo "$_bin_install_path/$_artifact" "$download_url"
+  curl -Lo "$_bin_install_path/$_artifact" "$download_url" || fail "Could not download $url"
 }
 
 _download "$ASDF_INSTALL_VERSION" "$ASDF_DOWNLOAD_PATH"
