feat(improve): add more improvements such as workflows, readmes, download scripts

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -1,15 +1,20 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -euo pipefail
 
-# [ -z "${ASDF_INSTALL_VERSION+x}" ] && echo "ASDF_INSTALL_VERSION is required" && exit 1
+[ -z "${ASDF_INSTALL_VERSION+x}" ] && echo "ASDF_INSTALL_VERSION is required" && exit 1
 
-github_repo="https://github.com/google/go-containerregistry/releases"
+current_script_path=${BASH_SOURCE[0]}
+plugin_dir=$(dirname "$(dirname "$current_script_path")")
+
+# shellcheck source=../lib/utils.bash
+source "${plugin_dir}/lib/utils.bash"
 
 _download() {
     local _version="$1"
     local _bin_install_path=$2
     local _artifact="go-containerregistry_Linux_x86_64.tar.gz"
-    
-    local download_url="$github_repo/download/v${_version}/$_artifact"
+
+    local download_url="$GH_REPO/releases/download/v${_version}/$_artifact"
 
     curl -Lo "$_bin_install_path/$_artifact" "$download_url"
 }
